services:
  - type: web
    name: retell-agent
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run render-start"
    envVars:
      - key: TOOL_SECRET
        sync: false
      - key: HR_TOKEN
        sync: false
      - key: HR_ID
        sync: false
