services:
  - type: web
    name: retell-agent
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: TOOL_SECRET
        sync: false
      - key: LLM_API_BASE
        value: https://api.openai.com/v1
      - key: LLM_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: LLM_TIMEOUT
        value: "5000"
      - key: MAX_CONCURRENT_LLM_REQUESTS
        value: "5"
