services:
  - type: web
    name: retell-agent
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install --prefer-online"
    startCommand: "npm run render-start"
    envVars:
      - key: TOOL_SECRET
        sync: false
    healthCheckPath: "/healthz"
    autoDeploy: true
